name: GTM Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.x'
      - name: Install dependencies
        run: go get .
      - name: Run tests
        run: go test -v ./...
